name: Deploy Function App

on:
  workflow_dispatch:
    inputs:
      slot-name:
        description: |
          Name of the slot to deploy to.
          Examples: staging, test, qa
          ⚠️ Must always provide a slot. Production is only via swap.
        required: true
      swap-to-prod:
        description: |
          Swap the slot to Production after deployment?
          Options:
            - false → Deploy only to the slot
            - true  → Deploy then swap to Production
        type: choice
        required: true
        options:
          - "false"
          - "true"
        default: "false"
      swap-only:
        description: |
          Skip deployment and swap slot directly to Production?
          Options:
            - false → Normal deployment (with optional swap)
            - true  → Only swap the existing slot
        type: choice
        required: true
        options:
          - "false"
          - "true"
        default: "false"
      environment:
        description: GitHub Environment for approval
        type: choice
        required: true
        options:
          - app1-test
          - app1-prod
          - app2-test
          - app2-prod

jobs:
  deploy-function-app:
    uses: ./.github/workflows/reusable-flow.yml
    with:
      function-app-name: function-2910
      resource-group: test-rg
      slot-name: ${{ github.event.inputs.slot-name }}
      swap-to-prod: ${{ github.event.inputs.swap-to-prod }}
      swap-only: ${{ github.event.inputs.swap-only }}
      environment: ${{ github.event.inputs.environment }}
      working-directory: functions
      package-path: functions/build.zip
      node-version: 20.x
    secrets: inherit