name: Deploy To Function APP (Test/Prod)

on:
  push:
    branches:
      - master
      - dev
      - devfeatures
      - development
  workflow_dispatch:
    inputs:
      deploy_to_prod:
        description: "Deploy-->Production  Set to True"
        required: false
        type: choice
        options:
          - true
          - false

jobs:
  deploy:
    uses: ./.github/workflows/functionapp-reusable-workflow.yml
    with:
      deploy_to_prod: ${{ inputs.deploy_to_prod }}
      working_directory: AzureFunctions
      node-version: 20.x
      test_function_app_name: test-functionapp-03
      prod_function_app_name: prod-functionapp-93
    secrets:
      PUBLISH_PROFILE_TEST: ${{ secrets.PUBLISH_PROFILE_TEST }}
      PUBLISH_PROFILE_PROD: ${{ secrets.PUBLISH_PROFILE_PROD }}