name: Invoke Reusable Function App Deploy

on:
  push:
    branches:
      - master
      - dev
      - devfeatures
      - development
  workflow_dispatch:
    inputs:
      deploy_to_prod:
        description: "Set to true to indicate you intend to deploy to production.
        required: false
        type: choice
        options:
          - true
          - false

jobs:
  deploy:
    uses: ./.github/workflows/functionapp-reusable-workflow.yml
    with:
      deploy_to_prod: ${{ inputs.deploy_to_prod }}
      functionapp_folder: AzureFunctions
      node-version: 20.x
      test_function_app_name: test-functionapp-01
      prod_function_app_name: prod-functionapp-05
    secrets:
      PUBLISH_PROFILE_TEST: ${{ secrets.PUBLISH_PROFILE_TEST }}
      PUBLISH_PROFILE_PROD: ${{ secrets.PUBLISH_PROFILE_PROD }}