name: Reusable Function App Deploy (Unified)

on:
  workflow_call:
    inputs:
      environment:
        description: "Set to 'prod' to force production deployment; otherwise branch logic decides (master => prod)."
        required: false
        type: string
        default: ""
      node-version:
        description: "Node.js version."
        required: false
        type: string
        default: "20.x"
      functionapp_folder:
        description: "Folder containing the Function App project."
        required: false
        type: string
        default: "."
      test_function_app_name:
        description: "Azure Function App name for TEST deployments."
        required: false
        type: string
      prod_function_app_name:
        description: "Azure Function App name for PROD deployments."
        required: false
        type: string
    secrets:
      PUBLISH_PROFILE_TEST:
        required: false
      PUBLISH_PROFILE_PROD:
        required: false

env:
  TEST_BRANCHES_JSON: '["dev","devfeatures","development"]'

jobs:

  validate:
    name: Validate / Build
    runs-on: ubuntu-latest
    outputs:
      is_prod: ${{ steps.flags.outputs.is_prod }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine prod flag
        id: flags
        run: |
          BRANCH="${GITHUB_REF_NAME}"
          if [ "${{ inputs.environment }}" = "prod" ] || [ "${BRANCH}" = "master" ]; then
            echo "is_prod=true" >> "$GITHUB_OUTPUT"
          else
            echo "is_prod=false" >> "$GITHUB_OUTPUT"
          fi
          echo "Branch: ${BRANCH}"
          echo "Forced environment input: '${{ inputs.environment }}'"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs['node-version'] }}

      - name: Install dependencies
        working-directory: ${{ inputs.functionapp_folder }}
        run: npm ci

      - name: Run tests
        working-directory: ${{ inputs.functionapp_folder }}
        run: npm test

      - name: Lint
        working-directory: ${{ inputs.functionapp_folder }}
        run: npm run lint --if-present

      - name: Build
        working-directory: ${{ inputs.functionapp_folder }}
        run: npm run build --if-present


  approval:
    name: Approval (Prod only)
    runs-on: ubuntu-latest
    needs: validate
    # If prod -> 'Production' (protected); else a no-review environment
    environment:
      name: ${{ needs.validate.outputs.is_prod == 'true' && 'Production'  }}
    steps:
      - name: Approval context
        run: |
          echo "Production flag: ${{ needs.validate.outputs.is_prod }}"
          if [ "${{ needs.validate.outputs.is_prod }}" = "true" ]; then
            echo "Awaiting (or passed) environment approval for Production."
          else
            echo "Non-prod deployment path (auto-approved)."
          fi


  deploy:
    name: Deploy (Test or Prod)
    runs-on: ubuntu-latest
    needs: [validate, approval]
    if: |
      needs.validate.outputs.is_prod == 'true' ||
      contains(fromJSON('["dev","devfeatures","development"]'), github.ref_name) }}
    env:
      IS_PROD: ${{ needs.validate.outputs.is_prod }}
      FUNCTION_APP_NAME: ${{ needs.validate.outputs.is_prod == 'true' && inputs.prod_function_app_name || inputs.test_function_app_name }}
      PUBLISH_PROFILE: ${{ needs.validate.outputs.is_prod == 'true' && secrets.PUBLISH_PROFILE_PROD || secrets.PUBLISH_PROFILE_TEST }}
      FUNCTIONAPP_FOLDER: ${{ inputs.functionapp_folder }}
    steps:
      - name: Preconditions
        run: |
          if [ "${IS_PROD}" = "true" ]; then
            [ -n "${FUNCTION_APP_NAME}" ] || { echo "::error::prod_function_app_name is required for production."; exit 1; }
            [ -n "${PUBLISH_PROFILE}" ] || { echo "::error::PUBLISH_PROFILE_PROD secret not provided."; exit 1; }
          else
            [ -n "${FUNCTION_APP_NAME}" ] || { echo "::error::test_function_app_name is required for test deployment."; exit 1; }
            [ -n "${PUBLISH_PROFILE}" ] || { echo "::error::PUBLISH_PROFILE_TEST secret not provided."; exit 1; }
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Package Function App
        run: |
          set -e
          cd "${FUNCTIONAPP_FOLDER}"
          zip -r ../functionapp.zip . -x "*.git*"
          ls -lh ../functionapp.zip

      - name: Show deployment context
        run: |
          echo "Branch: ${GITHUB_REF_NAME}"
          echo "IS_PROD: ${IS_PROD}"
          echo "Function App: ${FUNCTION_APP_NAME}"

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNCTION_APP_NAME }}
          package: functionapp.zip
          publish-profile: ${{ env.PUBLISH_PROFILE }}

      - name: Success Echo
        run: |
          if [ "${IS_PROD}" = "true" ]; then
            echo "✅ Production deployment succeeded for ${FUNCTION_APP_NAME}"
          else
            echo "✅ Test deployment succeeded for ${FUNCTION_APP_NAME}"
          fi