name: Reusable Function App Deployment

on:
  workflow_call:
    inputs:
      function-app-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      environment:
        required: true
        type: string
      slot-name:
        required: true
        type: string
      swap-to-prod:
        required: false
        type: string
        default: "false"
      swap-only:
        required: false
        type: string
        default: "false"
      working-directory:
        required: true
        type: string
      node-version:
        required: true
        type: string

    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  # -----------------------------
  # 1️⃣ VALIDATE & BUILD
  # -----------------------------
  validate_and_build:
    name: Validate & Build
    if: ${{ inputs.swap-only != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ inputs.working-directory }}

      - name: Lint Code
        run: npm run lint
        working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        run: npm test
        working-directory: ${{ inputs.working-directory }}

      - name: Build Project
        run: npm run build --if-present
        working-directory: ${{ inputs.working-directory }}

      - name: Create build.zip
        run: |
          cd ${{ inputs.working-directory }}
          zip -r build.zip .

      - name: Upload build.zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: function-build
          path: ${{ inputs.working-directory }}/build.zip

  # -----------------------------
  # 2️⃣ APPROVE BEFORE DEPLOY
  # -----------------------------
  approve_before_deploy:
    name: Await Approval for Slot Deployment
    needs: validate_and_build
    if: ${{ inputs.swap-only != 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "⏳ Awaiting approval to deploy to slot '${{ inputs.slot-name }}'"

  # -----------------------------
  # 3️⃣ DEPLOY FUNCTION APP
  # -----------------------------
  deploy:
    name: Deploy to Azure Function App
    needs: [validate_and_build, approve_before_deploy]
    if: ${{ inputs.swap-only != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download build.zip artifact
        uses: actions/download-artifact@v4
        with:
          name: function-build
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Slot Exists
        run: |
          echo "Checking slot '${{ inputs.slot-name }}'..."
          if ! az functionapp deployment slot show \
              --name ${{ inputs.function-app-name }} \
              --resource-group ${{ inputs.resource-group }} \
              --slot ${{ inputs.slot-name }} >/dev/null 2>&1; then
            echo "Creating slot '${{ inputs.slot-name }}'..."
            az functionapp deployment slot create \
              --name ${{ inputs.function-app-name }} \
              --resource-group ${{ inputs.resource-group }} \
              --slot ${{ inputs.slot-name }}
          else
            echo "Slot '${{ inputs.slot-name }}' already exists."
          fi

      - name: Deploy build.zip to Slot
        run: |
          echo "Deploying build.zip to slot '${{ inputs.slot-name }}'..."
          az functionapp deployment source config-zip \
            --src build.zip \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --slot ${{ inputs.slot-name }}
          echo "✅ Deployment complete!"

  # -----------------------------
  # 4️⃣ APPROVAL & SWAP LOGIC
  # -----------------------------
  approve_before_swap:
    name: Approve Swap to Production
    needs: deploy
    if: ${{ inputs.swap-only != 'true' && inputs.swap-to-prod == 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "⏳ Awaiting approval to swap slot '${{ inputs.slot-name }}' → Production..."

  swap:
    name: Swap Slot to Production
    needs: approve_before_swap
    if: ${{ inputs.swap-only != 'true' && inputs.swap-to-prod == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Swap Slots
        run: |
          az functionapp deployment slot swap \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --slot ${{ inputs.slot-name }} \
            --target-slot Production
          echo "✅ Slot swapped to Production!"

  # -----------------------------
  # 5️⃣ SWAP-ONLY MODE
  # -----------------------------
  approve_before_swap_only:
    name: Approve Swap-Only
    if: ${{ inputs.swap-only == 'true' && inputs.swap-to-prod == 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "⏳ Awaiting approval to swap existing slot '${{ inputs.slot-name }}' → Production..."

  swap_only:
    name: Swap Slot Only
    needs: approve_before_swap_only
    if: ${{ inputs.swap-only == 'true' && inputs.swap-to-prod == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Swap Slots
        run: |
          az functionapp deployment slot swap \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --slot ${{ inputs.slot-name }} \
            --target-slot Production
          echo "✅ Swap-only operation successful!"
