name: Reusable Function App Deployment

on:
  workflow_call:
    inputs:
      function-app-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      environment:
        required: true
        type: string
      slot-name:
        required: true
        type: string
      swap-to-prod:
        required: false
        type: string
        default: "false"
      swap-only:
        required: false
        type: string
        default: "false"
      working-directory:
        required: true
        type: string
      node-version:
        required: true
        type: string

    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  # -----------------------------
  # 1️⃣ VALIDATE, BUILD & ZIP
  # -----------------------------
  validate_and_build:
    name: Validate, Build & Package
    if: ${{ inputs.swap-only != 'true' }}
    runs-on: ubuntu-latest
    outputs:
      artifact-name: functionapp-artifact
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci --only=production
        working-directory: ${{ inputs.working-directory }}

      - name: Run Lint
        run: npm run lint
        working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        run: npm test
        working-directory: ${{ inputs.working-directory }}

      - name: Run Build
        run: npm run build
        working-directory: ${{ inputs.working-directory }}

      # ✅ Package function app so index.js is at the function folder
      - name: Zip Function App
        run: |
          cd ${{ inputs.working-directory }}
          # Remove unnecessary files/folders
          find . -type d -name "node_modules" -exec rm -rf {} +
          find . -type f -name "*.log" -delete
          find . -type d -name ".git" -exec rm -rf {} +
          # Zip everything (host.json + function folders)
          zip -r functionapp.zip ./*
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-artifact
          path: ${{ inputs.working-directory }}/functionapp.zip

  # -----------------------------
  # 2️⃣ APPROVE BEFORE SLOT DEPLOY
  # -----------------------------
  approve_before_slot_deploy:
    name: Await Approval
    needs: validate_and_build
    if: ${{ inputs.swap-only != 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "⏳ Awaiting approval for deployment to slot '${{ inputs.slot-name }}'"

  # -----------------------------
  # 3️⃣ DEPLOY TO SLOT
  # -----------------------------
  deploy_to_slot:
    name: Deploy to Function App Slot
    needs: approve_before_slot_deploy
    if: ${{ inputs.swap-only != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-artifact
          path: ./deploy

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Slot Exists
        run: |
          if ! az functionapp deployment slot show \
              --name ${{ inputs.function-app-name }} \
              --resource-group ${{ inputs.resource-group }} \
              --slot ${{ inputs.slot-name }} >/dev/null 2>&1; then
            echo "Slot '${{ inputs.slot-name }}' not found. Creating..."
            az functionapp deployment slot create \
              --name ${{ inputs.function-app-name }} \
              --resource-group ${{ inputs.resource-group }} \
              --slot ${{ inputs.slot-name }}
          else
            echo "Slot '${{ inputs.slot-name }}' exists. Skipping creation."
          fi

      - name: Deploy Function App ZIP
        run: |
          echo "Deploying to slot '${{ inputs.slot-name }}'..."
          az functionapp deployment source config-zip \
            --src ./deploy/functionapp.zip \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --slot ${{ inputs.slot-name }}

      # -----------------------------
      # 3️⃣a TEST HTTP TRIGGER WITH RETRY
      # -----------------------------
      - name: Test HTTP Trigger
        run: |
          SLOT_URL="https://${{ inputs.function-app-name }}-${{ inputs.slot-name }}.azurewebsites.net/api/HttpTriggerTest"
          MAX_RETRIES=5
          RETRY_DELAY=5
          attempt=1

          while [ $attempt -le $MAX_RETRIES ]; do
            echo "Attempt $attempt: Testing HTTP trigger at $SLOT_URL ..."
            
            GET_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$SLOT_URL?name=Krishna")
            POST_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" -d '{"name":"Krishna"}' "$SLOT_URL")

            if [ "$GET_RESPONSE" -eq 200 ] && [ "$POST_RESPONSE" -eq 200 ]; then
              echo "✅ HTTP Trigger GET and POST requests succeeded"
              break
            fi

            echo "❌ Attempt $attempt failed (GET=$GET_RESPONSE, POST=$POST_RESPONSE), retrying in $RETRY_DELAY seconds..."
            sleep $RETRY_DELAY
            attempt=$((attempt+1))
          done

          if [ "$GET_RESPONSE" -ne 200 ] || [ "$POST_RESPONSE" -ne 200 ]; then
            echo "❌ HTTP Trigger test failed after $MAX_RETRIES attempts"
            exit 1
          fi

  # -----------------------------
  # 4️⃣ APPROVE & SWAP TO PROD
  # -----------------------------
  approve_and_swap:
    name: Approve Swap
    needs: deploy_to_slot
    if: ${{ inputs.swap-to-prod == 'true' && inputs.swap-only != 'true' }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo "⏳ Awaiting approval to swap '${{ inputs.slot-name }}' to Production..."

  swap_slot:
    name: Swap Slot to Production
    needs: approve_and_swap
    if: ${{ inputs.swap-to-prod == 'true' && inputs.swap-only != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap Slots
        run: |
          echo "Swapping slot '${{ inputs.slot-name }}' to Production..."
          az functionapp deployment slot swap \
            --resource-group ${{ inputs.resource-group }} \
            --name ${{ inputs.function-app-name }} \
            --slot ${{ inputs.slot-name }} \
            --target-slot Production
          echo "✅ Swap successful!"
