name: Reusable Function App Deployment

on:
  workflow_call:
    inputs:
      function-app-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      slot-name:
        required: true
        type: string
      swap-to-prod:
        required: true
        type: boolean
      swap-only:
        required: true
        type: boolean
      environment:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      node-version:
        required: true
        type: string

jobs:
  validate_and_build:
    name: "Validate, Test, Build and Vulnerability Scan"
    if: ${{ inputs.swap-only == false }}
    runs-on: ubuntu-latest
    outputs:
      artifact-name: validate-artifact
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Dependencies
        run: npm install
        working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        run: npm test
        working-directory: ${{ inputs.working-directory }}

      - name: Run Build
        run: npm run build
        working-directory: ${{ inputs.working-directory }}

      - name: Run Lint
        run: npm run lint
        working-directory: ${{ inputs.working-directory }}

      - name: Run Vulnerability Scan
        run: npm audit
        working-directory: ${{ inputs.working-directory }}

      - name: Zip Artifact
        run: |
          cd ${{ inputs.working-directory }}
          zip -r ../app.zip .
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: validate-artifact
          path: ${{ inputs.working-directory }}/../app.zip

  approve_staging_deployment:
    name: "Approve Staging/Test Deployment"
    if: ${{ inputs.swap-only == false }}
    needs: validate_and_build
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Await Approval for Staging Deployment
        run: echo "Approved for deployment to staging/test"

  deploy_to_staging:
    name: "Deploy to Staging/Test"
    if: ${{ inputs.swap-only == false }}
    needs: approve_staging_deployment
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: validate-artifact
          path: app-deploy

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Function App to Slot
        run: |
          az functionapp deployment source config-zip \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --slot ${{ inputs.slot-name }} \
            --src app-deploy/app.zip

  approve_staging_to_production:
    name: "Approve Staging to Production Swap"
    if: ${{ inputs.swap-to-prod == true && inputs.swap-only == false }}
    needs: deploy_to_staging
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Await Approval to Swap Staging to Production
        run: echo "Approved to swap staging slot to production"

  swap_staging_to_production:
    name: "Swap Staging Slot to Production"
    if: ${{ inputs.swap-to-prod == true }}
    needs: [approve_staging_to_production, approve_staging_deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap Slot to Production
        run: |
          az functionapp deployment slot swap \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --slot ${{ inputs.slot-name }}

  approve_swap_only_to_production:
    name: "Approve Swap Only to Production"
    if: ${{ inputs.swap-only == true && inputs.swap-to-prod == true }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: Await Approval for Swap Only
        run: echo "Approved to swap only to production"

  swap_only_to_production:
    name: "Swap Only Slot to Production"
    if: ${{ inputs.swap-only == true && inputs.swap-to-prod == true }}
    needs: approve_swap_only_to_production
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Swap Slot to Production
        run: |
          az functionapp deployment slot swap \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --slot ${{ inputs.slot-name }}
