name: Reusable Function App Deployment

on:
  workflow_call:
    inputs:
      function-app-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      environment:
        required: true
        type: string
      slot-name:
        required: true
        type: string
      swap-to-prod:
        required: false
        type: string
        default: "false"
      swap-only:
        required: false
        type: string
        default: "false"
      working-directory:
        required: true
        type: string
      node-version:
        required: true
        type: string

    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  # -----------------------------
  # 1️⃣ VALIDATE, BUILD & PACKAGE
  # -----------------------------
  validate_and_build:
    name: Validate, Build & Package
    runs-on: ubuntu-latest
    outputs:
      artifact-name: functionapp-artifact
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci --only=production
        working-directory: ${{ inputs.working-directory }}

      - name: Run Lint
        run: npm run lint
        working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        run: npm test
        working-directory: ${{ inputs.working-directory }}

      - name: Run Build
        run: npm run build
        working-directory: ${{ inputs.working-directory }}

      # ✅ Package only function folders + host.json
      - name: Zip Function App
        run: |
          cd ${{ inputs.working-directory }}
          find . -type d -name "node_modules" -exec rm -rf {} +
          find . -type f -name "*.log" -delete
          find . -type d -name ".git" -exec rm -rf {} +
          zip -r functionapp.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-artifact
          path: ${{ inputs.working-directory }}/functionapp.zip

  # -----------------------------
  # 2️⃣ DEPLOY TO SLOT USING PUBLISH PROFILE
  # -----------------------------
  deploy_to_slot:
    name: Deploy to Function App Slot
    needs: validate_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-artifact
          path: ./deploy

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Slot Exists
        run: |
          if ! az functionapp deployment slot show \
              --name ${{ inputs.function-app-name }} \
              --resource-group ${{ inputs.resource-group }} \
              --slot ${{ inputs.slot-name }} >/dev/null 2>&1; then
            echo "Slot '${{ inputs.slot-name }}' not found. Creating..."
            az functionapp deployment slot create \
              --name ${{ inputs.function-app-name }} \
              --resource-group ${{ inputs.resource-group }} \
              --slot ${{ inputs.slot-name }}
          else
            echo "Slot '${{ inputs.slot-name }}' exists. Skipping creation."
          fi

      - name: Get Publish Profile
        id: pubprofile
        run: |
          echo "Fetching publish profile..."
          PUB_PROFILE=$(az functionapp deployment list-publishing-profiles \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --slot ${{ inputs.slot-name }} \
            --query "[?contains(publishMethod,'MSDeploy')].publishUrl" -o tsv)
          echo "publish-profile-url=$PUB_PROFILE" >> $GITHUB_OUTPUT

      - name: Deploy using Publish Profile
        run: |
          echo "Deploying artifact via publish profile..."
          curl -X POST \
            -u "$PUB_PROFILE" \
            --data-binary @./deploy/functionapp.zip \
            https://${{ inputs.function-app-name }}-${{ inputs.slot-name }}.scm.azurewebsites.net/api/zipdeploy
