name: Deploy Function App Slot

on:
  workflow_dispatch:

jobs:
  deploy-node-func:
    uses: ./.github/workflows/testing-cicd-reusable.yml
    with:
      function-app-name: 'function2910'
      resource-group: 'my-rg'
      slot-name: 'staging'
      functions-folder: 'src'
      node-version: '20'
    secrets: inherit
