name: Trigger Function App Deployment

on:
  workflow_dispatch:   # allows manual trigger
    inputs:
      function-app-name:
        description: 'Azure Function App name'
        required: true
      resource-group:
        description: 'Azure Resource Group name'
        required: true
      slot-name:
        description: 'Deployment slot name'
        required: true
      build-zip-path:
        description: 'Path to the prebuilt zip file'
        required: true
        default: 'functionss/build.zip'
      working-directory:
        description: 'Working directory for npm install and audit'
        required: true
        default: 'functionss'
      node-version:
        description: 'Node.js version for npm audit'
        required: false
        default: '20'

jobs:
  deploy-functionapp:
    uses: ./.github/workflows/reusable-deploy.yml  # path to your reusable workflow
    with:
      function-app-name: function2910
      resource-group: my-rg
      slot-name: staging
      build-zip-path: ${{ github.event.inputs.build-zip-path }}
      working-directory: ${{ github.event.inputs.working-directory }}
      node-version: ${{ github.event.inputs.node-version }}
