name: Reusable Build & Deploy Function App (Node.js + Slot Creation)

on:
  workflow_call:
    inputs:
      function-app-name:
        required: true
        type: string
      resource-group:
        required: true
        type: string
      slot-name:
        required: true
        type: string
      functions-folder:
        required: true
        type: string
      node-version:
        required: false
        type: string
        default: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies & package
        working-directory: ${{ inputs.functions-folder }}
        run: |
          npm install --production
          zip -r ../functionapp.zip host.json package.json src

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: functionapp-zip
          path: functionapp.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: functionapp-zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Slot if not exists
        id: create-slot
        continue-on-error: true
        run: |
          echo "Checking if slot exists..."
          SLOT_EXISTS=$(az functionapp deployment slot list \
            --name ${{ inputs.function-app-name }} \
            --resource-group ${{ inputs.resource-group }} \
            --query "[?name=='${{ inputs.slot-name }}'] | length(@)" -o tsv)

          if [ "$SLOT_EXISTS" -eq 0 ]; then
            echo "Creating slot: ${{ inputs.slot-name }}"
            az functionapp deployment slot create \
              --name ${{ inputs.function-app-name }} \
              --resource-group ${{ inputs.resource-group }} \
              --slot ${{ inputs.slot-name }} \
              --configuration-source ${{ inputs.function-app-name }}
          else
            echo "Slot ${{ inputs.slot-name }} already exists."
          fi

      - name: Deploy Function App Code
        uses: azure/functions-action@v1
        with:
          app-name: ${{ inputs.function-app-name }}
          package: functionapp.zip
          slot-name: ${{ inputs.slot-name }}
