name: Validate, Build, Artifact & Node.js Scan

on:
  workflow_call:
    inputs:
      working-directory:
        description: Node.js project folder relative to repo root (where package.json exists)
        required: true
        type: string
      node-version:
        description: Node.js version to use
        required: true
        type: string

jobs:
  validate_build:
    name: Validate, Build & Upload Artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Verify working directory exists
      - name: Verify working directory exists
        run: |
          if [ ! -d "${{ inputs.working-directory }}" ]; then
            echo "❌ Folder ${{ inputs.working-directory }} does not exist!"
            exit 1
          else
            echo "✅ Folder ${{ inputs.working-directory }} found."
          fi

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      # Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.working-directory }}

      # Lint
      - name: Lint
        run: npm run lint
        working-directory: ${{ inputs.working-directory }}

      # Test
      - name: Run tests
        run: npm test
        working-directory: ${{ inputs.working-directory }}

      # Build
      - name: Build
        run: npm run build
        working-directory: ${{ inputs.working-directory }}

      # Zip the **entire code folder + build + package.json** as artifact
      - name: Zip Full Artifact
        run: |
          artifact_folder="artifact"
          mkdir -p $artifact_folder
          cp -r ${{ inputs.working-directory }}/* $artifact_folder/
          zip -r full-artifact.zip $artifact_folder/

      # Upload artifact
      - name: Upload Full Artifact
        uses: actions/upload-artifact@v4
        with:
          name: full-artifact
          path: full-artifact.zip

  scan:
    name: Download Artifact & Node.js Vulnerability Scan
    needs: validate_build
    runs-on: ubuntu-latest
    steps:
      # Download artifact
      - name: Download Full Artifact
        uses: actions/download-artifact@v4
        with:
          name: full-artifact
          path: ./artifact

      # Unzip artifact
      - name: Unzip Full Artifact
        run: unzip ./artifact/full-artifact.zip -d ./artifact

      # Node.js vulnerability scan
      - name: Node.js Vulnerability Scan
        run: |
          echo "🔍 Running vulnerability scan..."
          npm install
          if npm audit --audit-level=high; then
            echo "✅ Vulnerability scan passed."
          else
            echo "❌ Vulnerability scan failed! Fix high/critical issues before deploying."
            exit 1
          fi
        working-directory: ./artifact
